Create pull_request_template.md
BYU-PCCL/HolodeckPythonBinding pull request #444
Opened 2021-01-28 18:05 UTC by chris-luangrath

Pull request template

2021-01-28 19:27 UTC, vinhowe requested changes

2021-01-28 19:27 UTC, vinhowe commented on pull_request_template.md
> +### Pull Request Checklist
Can you rewrite this in active voice? "I wrote tests," "My code passed," etc.

2021-02-08 19:27 UTC, vinhowe commented
LGTM. @daniekpo, what do you think?

2021-02-10 18:43 UTC, daniekpo approved these changes
LGTM

2021-02-10 18:43 UTC, daniekpo commented
> LGTM. @daniekpo, what do you think?

Looks good to me.

2021-02-10 18:56 UTC, vinhowe approved these changes

2021-02-11 18:35 UTC, merged